global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['flask-app-service:5000']
    scrape_interval: 5s

  - job_name: 'jenkins'
    metrics_path: /prometheus/
    static_configs:
      - targets: ['jenkins:8080']
    scrape_interval: 10s
