{
 "title": "Jenkins Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Pipeline Runs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_total" }
   ]
  },
  {
   "title": "Build Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_build_health" }
   ]
  },
  {
   "title": "Build Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    { "expr": "jenkins_build_duration_seconds", "legendFormat": "{{jobName}}" }
   ]
  },
  {
   "title": "Success Rate by Job",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_job_success_rate", "legendFormat": "{{job}}" }
   ]
  }
 ]
}