replicaCount: 1

image:
  repository: bitnami/minideb
  tag: latest
  pullPolicy: IfNotPresent

# Application configuration
agentName: "Fabi"
appVersion: "1.0.0"  # Default version to use

nexus:
  url: "http://nexus:8081"
  repository: "raw_repo"
  path: "app-flask"  # Base path without version

service:
  type: NodePort
  port: 5000
  targetPort: 5000

livenessProbe:
  path: /health-check
  initialDelaySeconds: 10
  periodSeconds: 30

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: flask-app.local
      paths:
        - path: /
          pathType: Prefix
        - path: /health-check
          pathType: Prefix
